In [7]:
import numpy as np
import pandas as pd
from IPython.display import display 

df = pd.read_csv(filepath_or_buffer='/Users/sachita/Documents/Projects/Summer/Winter2018/train_data.txt', 
                 delimiter='\t')

In [8]:
df_elim = df.loc[:, ['date', 'lat', 'lon', 'cld', 'gfed', 'npp', 'pr', 'prev_ba', 'rh', 'ts', 'ftmap0',
 'ftmap1',
 'ftmap2',
 'ftmap3',
 'ftmap4',
 'ftmap5',
 'ftmap6',
 'ftmap7',
 'ftmap8',
 'ftmap9',
 'ftmap10', 'pop']]

df_elim.head()

,date,lat,lon,cld,gfed,npp,pr,prev_ba,rh,ts,...,ftmap2,ftmap3,ftmap4,ftmap5,ftmap6,ftmap7,ftmap8,ftmap9,ftmap10,pop
0,2002-1-16,5.25,95.25,62.5808,0.0,0.117142,6.58815,0.000000,78.0881,300.061,...,0.388614,0.000556,0.000000,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.9571
1,2002-1-16,5.25,95.75,61.6344,0.0,0.113316,5.22508,0.000301,78.4690,299.843,...,0.800540,0.000278,0.000000,0.000278,0.001944,0.007778,0.051944,0.002222,0.089722,95.9084
2,2002-1-16,5.25,96.25,59.7508,0.0,0.114087,4.35532,0.000050,78.8500,299.626,...,0.460561,0.001944,0.001667,0.000833,0.002222,0.008889,0.008611,0.001389,0.026944,107.6620
3,2002-1-16,5.25,96.75,57.8672,0.0,0.115081,2.64581,0.000118,79.2310,299.408,...,0.381391,0.001667,0.000556,0.000278,0.001667,0.004722,0.017222,0.001111,0.062500,114.6420
4,2002-1-16,5.25,97.25,55.9836,0.0,0.090279,3.64089,0.000006,79.6119,299.191,...,0.252776,0.003889,0.002222,0.003611,0.006944,0.013333,0.028611,0.005833,0.065833,202.4680

In [9]:
#Convert to log
#df_elim['class'] = df['gfed'].apply(lambda x: 0 if x==0 else 1)
df_elim['log10'] = df['gfed'].apply(lambda x: np.log10(x) if x!=0 else 0)
df_elim.head()

,date,lat,lon,cld,gfed,npp,pr,prev_ba,rh,ts,...,ftmap3,ftmap4,ftmap5,ftmap6,ftmap7,ftmap8,ftmap9,ftmap10,pop,log10
0,2002-1-16,5.25,95.25,62.5808,0.0,0.117142,6.58815,0.000000,78.0881,300.061,...,0.000556,0.000000,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.9571,0.0
1,2002-1-16,5.25,95.75,61.6344,0.0,0.113316,5.22508,0.000301,78.4690,299.843,...,0.000278,0.000000,0.000278,0.001944,0.007778,0.051944,0.002222,0.089722,95.9084,0.0
2,2002-1-16,5.25,96.25,59.7508,0.0,0.114087,4.35532,0.000050,78.8500,299.626,...,0.001944,0.001667,0.000833,0.002222,0.008889,0.008611,0.001389,0.026944,107.6620,0.0
3,2002-1-16,5.25,96.75,57.8672,0.0,0.115081,2.64581,0.000118,79.2310,299.408,...,0.001667,0.000556,0.000278,0.001667,0.004722,0.017222,0.001111,0.062500,114.6420,0.0
4,2002-1-16,5.25,97.25,55.9836,0.0,0.090279,3.64089,0.000006,79.6119,299.191,...,0.003889,0.002222,0.003611,0.006944,0.013333,0.028611,0.005833,0.065833,202.4680,0.0

In [10]:
#Getting classes from log values

limits = np.linspace(-6, 0, 25) #list of upper bounds of each bin
labels = list(range(1, 25))
bin_labels=[str(x) for x in labels]
valuepass = df_elim['log10'].tolist()

final_labels = pd.cut(valuepass, bins=limits, labels=bin_labels, include_lowest=True)
df_elim = df_elim.assign(labels=final_labels)

def define_label(row):
    if row['log10']==0:
        return 0
    else:
        return row['labels']

df_elim['final_label'] = df_elim.apply(define_label, axis = 1)
df_elim.head()

,date,lat,lon,cld,gfed,npp,pr,prev_ba,rh,ts,...,ftmap5,ftmap6,ftmap7,ftmap8,ftmap9,ftmap10,pop,log10,labels,final_label
0,2002-1-16,5.25,95.25,62.5808,0.0,0.117142,6.58815,0.000000,78.0881,300.061,...,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.9571,0.0,24,0
1,2002-1-16,5.25,95.75,61.6344,0.0,0.113316,5.22508,0.000301,78.4690,299.843,...,0.000278,0.001944,0.007778,0.051944,0.002222,0.089722,95.9084,0.0,24,0
2,2002-1-16,5.25,96.25,59.7508,0.0,0.114087,4.35532,0.000050,78.8500,299.626,...,0.000833,0.002222,0.008889,0.008611,0.001389,0.026944,107.6620,0.0,24,0
3,2002-1-16,5.25,96.75,57.8672,0.0,0.115081,2.64581,0.000118,79.2310,299.408,...,0.000278,0.001667,0.004722,0.017222,0.001111,0.062500,114.6420,0.0,24,0
4,2002-1-16,5.25,97.25,55.9836,0.0,0.090279,3.64089,0.000006,79.6119,299.191,...,0.003611,0.006944,0.013333,0.028611,0.005833,0.065833,202.4680,0.0,24,0

In [11]:
df = df_elim.drop(['log10', 'labels', 'prev_ba'], axis=1)
df.head()

,date,lat,lon,cld,gfed,npp,pr,rh,ts,ftmap0,...,ftmap3,ftmap4,ftmap5,ftmap6,ftmap7,ftmap8,ftmap9,ftmap10,pop,final_label
0,2002-1-16,5.25,95.25,62.5808,0.0,0.117142,6.58815,78.0881,300.061,0.540837,...,0.000556,0.000000,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.9571,0
1,2002-1-16,5.25,95.75,61.6344,0.0,0.113316,5.22508,78.4690,299.843,0.043611,...,0.000278,0.000000,0.000278,0.001944,0.007778,0.051944,0.002222,0.089722,95.9084,0
2,2002-1-16,5.25,96.25,59.7508,0.0,0.114087,4.35532,78.8500,299.626,0.481117,...,0.001944,0.001667,0.000833,0.002222,0.008889,0.008611,0.001389,0.026944,107.6620,0
3,2002-1-16,5.25,96.75,57.8672,0.0,0.115081,2.64581,79.2310,299.408,0.521116,...,0.001667,0.000556,0.000278,0.001667,0.004722,0.017222,0.001111,0.062500,114.6420,0
4,2002-1-16,5.25,97.25,55.9836,0.0,0.090279,3.64089,79.6119,299.191,0.606388,...,0.003889,0.002222,0.003611,0.006944,0.013333,0.028611,0.005833,0.065833,202.4680,0

In [12]:
df.to_csv(path_or_buf='/Users/sachita/Documents/Projects/Summer/Winter2018/firedata/fire_mod.csv', sep=',', index=False)

In [7]:
#Sort by lat lon and cut up into discrete datasets
df = df.sort_values(['lat', 'lon'])
df

,date,lat,lon,cld,gfed,npp,pr,prev_ba,rh,ts,...,ftmap3,ftmap4,ftmap5,ftmap6,ftmap7,ftmap8,ftmap9,ftmap10,pop,final_label
0,2002-1-16,5.25,95.25,62.5808,0.000000,0.117142,6.588150,0.000000,78.0881,300.061,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
3120,2002-2-14,5.25,95.25,49.1459,0.000000,0.128032,1.776700,0.000000,74.7004,300.217,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
6240,2002-3-16,5.25,95.25,49.6476,0.000000,0.153049,4.861690,0.000000,77.4807,300.484,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
9360,2002-4-15,5.25,95.25,58.8578,0.000000,0.119791,8.699500,0.000000,79.6542,300.471,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
12480,2002-5-16,5.25,95.25,55.8353,0.000000,0.128032,5.002020,0.000000,73.7806,301.261,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
15600,2002-6-15,5.25,95.25,50.7222,0.000000,0.110667,1.893750,0.000000,72.2312,301.178,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
18720,2002-7-16,5.25,95.25,60.9881,0.000470,0.104486,3.062180,0.000000,76.3908,300.653,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,11
21840,2002-8-16,5.25,95.25,65.0267,0.000230,0.101248,2.660810,0.000000,76.6764,300.410,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,10
24960,2002-9-15,5.25,95.25,67.2224,0.000000,0.070933,4.200250,0.000000,77.3072,300.112,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
28080,2002-10-16,5.25,95.25,70.1146,0.000000,0.085943,8.897660,0.000000,80.4748,300.000,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
31200,2002-11-15,5.25,95.25,77.1713,0.000000,0.085060,8.490000,0.000000,81.6541,299.956,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
34320,2002-12-16,5.25,95.25,75.9166,0.000000,0.107135,6.096290,0.000000,81.2547,300.253,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
37440,2003-1-16,5.25,95.25,67.0251,0.000000,0.113610,5.184680,0.000058,79.3385,299.930,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
40560,2003-2-14,5.25,95.25,60.2878,0.000000,0.116259,3.071250,0.000058,78.2905,300.166,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
43680,2003-3-16,5.25,95.25,65.7519,0.000000,0.140688,7.125970,0.000058,78.8156,300.314,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
46800,2003-4-15,5.25,95.25,54.5281,0.000000,0.140099,4.454750,0.000058,79.4482,300.704,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
49920,2003-5-16,5.25,95.25,59.8453,0.000000,0.115376,5.593060,0.000058,76.1536,301.259,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
53040,2003-6-15,5.25,95.25,62.8649,0.000000,0.108312,2.898750,0.000058,74.0897,301.088,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
56160,2003-7-16,5.25,95.25,61.5504,0.000534,0.117142,1.913710,0.000058,77.0406,300.535,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,11
59280,2003-8-16,5.25,95.25,65.5864,0.000000,0.107135,3.938950,0.000058,77.6831,300.407,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
62400,2003-9-15,5.25,95.25,70.1105,0.000000,0.104486,3.566000,0.000058,77.3698,300.294,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
65520,2003-10-16,5.25,95.25,74.6764,0.000000,0.092124,5.891130,0.000058,80.3232,299.953,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
68640,2003-11-15,5.25,95.25,70.3217,0.000000,0.102720,11.511700,0.000058,82.6178,299.756,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
71760,2003-12-16,5.25,95.25,72.5535,0.000000,0.091241,6.845080,0.000058,78.7765,299.983,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
74880,2004-1-16,5.25,95.25,66.5713,0.000000,0.125383,5.020650,0.000044,79.4796,300.108,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
78000,2004-2-15,5.25,95.25,63.5113,0.000000,0.109195,3.488020,0.000044,79.5943,300.024,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
81120,2004-3-16,5.25,95.25,53.5435,0.000000,0.131564,8.829440,0.000044,79.7964,300.116,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
84240,2004-4-15,5.25,95.25,57.6685,0.000000,0.105074,6.401750,0.000044,78.5513,300.759,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
87360,2004-5-16,5.25,95.25,58.9243,0.000000,0.110961,3.644270,0.000044,70.3143,301.645,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
90480,2004-6-15,5.25,95.25,62.0389,0.000000,0.101542,3.028500,0.000044,74.3267,301.130,...,0.000556,0.0,0.000278,0.000000,0.004167,0.014722,0.000278,0.046667,58.957100,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433679,2013-7-16,49.75,99.75,53.9619,0.000000,0.039981,5.105080,0.000000,81.9336,284.302,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
436799,2013-8-16,49.75,99.75,54.2063,0.000000,0.037297,5.393230,0.000000,87.1363,283.247,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
439919,2013-9-15,49.75,99.75,40.9761,0.000000,0.001695,1.426750,0.000000,78.9384,275.475,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
443039,2013-10-16,49.75,99.75,36.4756,0.000000,0.000000,1.054350,0.000000,79.6997,267.801,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
446159,2013-11-15,49.75,99.75,37.9575,0.000000,0.000000,0.402750,0.000000,90.4238,260.797,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
449279,2013-12-16,49.75,99.75,37.1329,0.000000,0.000000,1.437580,0.000000,90.2305,255.528,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
452399,2014-1-16,49.75,99.75,29.1727,0.000000,0.000000,0.024193,0.000000,89.1954,251.801,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
455519,2014-2-14,49.75,99.75,21.7553,0.000000,0.000000,0.375268,0.000000,83.4709,248.126,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
458639,2014-3-16,49.75,99.75,26.1130,0.000000,0.000000,0.020323,0.000000,85.0423,261.486,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
461759,2014-4-15,49.75,99.75,42.2187,0.000000,0.000000,1.041250,0.000000,84.4852,272.016,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
464879,2014-5-16,49.75,99.75,49.6441,0.000000,0.001130,1.006940,0.000000,86.3215,274.730,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
467999,2014-6-15,49.75,99.75,51.0275,0.000000,0.026277,3.741750,0.000000,87.5862,281.485,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
471119,2014-7-16,49.75,99.75,45.1795,0.000000,0.045067,7.149190,0.000000,78.7178,285.147,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
474239,2014-8-16,49.75,99.75,45.6338,0.000000,0.027549,3.043790,0.000000,74.1045,283.503,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
477359,2014-9-15,49.75,99.75,39.9272,0.000000,0.001130,3.965000,0.000000,73.6178,276.236,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
480479,2014-10-16,49.75,99.75,39.6515,0.000000,0.000000,2.732420,0.000000,82.8846,269.738,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
483599,2014-11-15,49.75,99.75,28.4105,0.000000,0.000000,1.938250,0.000000,86.0072,258.183,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
486719,2014-12-16,49.75,99.75,26.6107,0.000000,0.000000,0.012581,0.000000,89.3754,251.037,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
489839,2015-1-16,49.75,99.75,28.4950,0.000000,0.000000,0.018871,0.000000,88.6362,252.997,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
492959,2015-2-14,49.75,99.75,25.1069,0.000000,0.000000,0.050357,0.000000,87.2416,254.144,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
496079,2015-3-16,49.75,99.75,34.9453,0.000000,0.000000,0.658790,0.000000,87.9338,259.552,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
499199,2015-4-15,49.75,99.75,34.4025,0.000000,0.000000,0.694750,0.000000,81.7830,270.394,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
502319,2015-5-16,49.75,99.75,43.9728,0.000000,0.000848,1.475810,0.000000,81.2508,275.007,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
505439,2015-6-15,49.75,99.75,43.5191,0.000000,0.024017,1.501250,0.000000,72.5043,283.468,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
508559,2015-7-16,49.75,99.75,47.1315,0.000000,0.032635,3.863470,0.000000,75.5144,286.323,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
511679,2015-8-16,49.75,99.75,46.9597,0.000000,0.030657,7.820320,0.000000,72.2040,285.395,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
514799,2015-9-15,49.75,99.75,49.4121,0.000000,0.003108,3.713250,0.000000,80.9300,275.773,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
517919,2015-10-16,49.75,99.75,36.9317,0.000000,0.000000,0.453629,0.000000,79.8578,269.983,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
521039,2015-11-15,49.75,99.75,37.1694,0.000000,0.000000,0.703750,0.000000,92.5257,257.732,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0
524159,2015-12-16,49.75,99.75,35.2649,0.000000,0.000000,0.532016,0.000000,94.9931,255.914,...,0.005833,0.0,0.003056,0.023611,0.013333,0.001111,0.925254,0.000000,0.134546,0

In [8]:
#14 years worth of monthly data => 168 readings/lat-lon pair
def splitDataFrameIntoSmaller(df, chunkSize): 
    listOfDf = list()
    numberChunks = len(df) // chunkSize 
    print(numberChunks)
    for i in range(numberChunks):
        listOfDf.append(df[i*chunkSize:(i+1)*chunkSize])
    return listOfDf

result = splitDataFrameIntoSmaller(df, 168)

3120

In [10]:
#mockup to just save the first lat-lon pair as its own csv file
result[1].to_csv(path_or_buf='/Users/sachita/Documents/Projects/Summer/Winter2018/firedata/525_9575.csv', sep=',', index=False)

In [ ]:
# #function to save every dataframe of this setup as a separate csv file
# dest = '/Users/sachita/Documents/Projects/Summer/Winter2018/firedata/'#enter destination

# for item in result:
    
#     fname=str(int(item.loc[0, 'lat']*100))+'_'+str(int(item.loc[0, 'lon']*100))
#     pathname=dest+fname
#     item.to_csv(path_or_buf=pathname, sep=',', index=False)